server:
  port: 8828

spring:
  application:
    name: customers
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/customer
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

