spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
#  cloud:
#    gateway:
#      routes:
#        - id: customer
#          uri: lb://CUSTOMERS
#          predicates:
#            - Path=/api/v1/customers/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8080/realms/practice-keycloak

server:
  port: 8025

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
